function makeId(length = 5) {
  var txt = ""
  var possible =
    "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789"
  for (let i = 0; i < length; i++) {
    txt += possible.charAt(Math.floor(Math.random() * possible.length))
  }
  return txt
}

function debounce(func, timeout = 300) {
  let timer
  return (...args) => {
    clearTimeout(timer)
    timer = setTimeout(() => {
      func.apply(this, args)
    }, timeout)
  }
}

function getRandomInt(min, max) {
  min = Math.ceil(min)
  max = Math.floor(max)
  return Math.floor(Math.random() * (max - min + 1)) + min
}

function generateRandomName() {
  const names = [
    "Jhon",
    "Wick",
    "Strong",
    "Dude",
    "Yep",
    "Hello",
    "World",
    "Power",
    "Goku",
    "Super",
    "Hi",
    "You",
    "Are",
    "Awesome",
  ]
  const famName = [
    "star",
    "kamikaza",
    "family",
    "eat",
    "some",
    "banana",
    "brock",
    "david",
    "gun",
    "walk",
    "talk",
    "car",
    "wing",
    "yang",
    "snow",
    "fire",
  ]
  return (
    names[Math.floor(Math.random() * names.length)] +
    famName[Math.floor(Math.random() * names.length)]
  )
}

function generateRandomImg() {
  //try to get diff img every time
  return "pro" + Math.floor(Math.random() * 17 + 1) + ".png"
}

function timeAgo(ms = new Date()) {
  const date = ms instanceof Date ? ms : new Date(ms)
  const formatter = new Intl.RelativeTimeFormat("en")
  const ranges = {
    years: 3600 * 24 * 365,
    months: 3600 * 24 * 30,
    weeks: 3600 * 24 * 7,
    days: 3600 * 24,
    hours: 3600,
    minutes: 60,
    seconds: 1,
  }
  const secondsElapsed = (date.getTime() - Date.now()) / 1000
  for (let key in ranges) {
    if (ranges[key] < Math.abs(secondsElapsed)) {
      const delta = secondsElapsed / ranges[key]
      let time = formatter.format(Math.round(delta), key)
      if (time.includes("in")) {
        time = time.replace("in ", "")
        time = time.replace("ago", "")
        time += " ago"
      }
      return time //? time : 'Just now'
    }
  }
}

module.exports = {
  makeId,
  getRandomInt,
  debounce,
  generateRandomName,
  timeAgo,
  generateRandomImg,
}

const names = [
  "Sydney Arroyo",
  "Tania Henson",
  "Mikayla Woodard",
  "Brenton Walter",
  "Catalina Lawrence",
  "Deon Wolf",
  "Destinee Dominguez",
  "Evan Obrien",
  "Reece Savage",
  "Adalyn Sloan",
  "Kian Steele",
  "Cullen Buck",
  "Anderson Cortez",
  "Camron Swanson",
  "Melany Leach",
  "Ean Petty",
  "Alaina Malone",
  "Lamont Schmidt",
  "Jace Abbott",
  "Rohan Foley",
  "Neil Golden",
  "Duncan Harper",
  "Emmy Davila",
  "Payten Gibson",
  "Nathaly Maynard",
  "Yuliana Quinn",
  "Kaylen Ramirez",
  "Justine Wilkins",
  "Madilynn Duncan",
  "Neil Rasmussen",
  "Ibrahim Peters",
  "Asher Lucero",
  "Kaitlin Mckee",
  "Andrea Hinton",
  "Madilyn Hendricks",
  "Brylee Frost",
  "Tania Sharp",
  "Erin Castro",
  "Addison Landry",
  "Saige Booker",
  "Aylin Mendoza",
  "Henry Rush",
  "Junior Pollard",
  "Mariana Mcpherson",
  "Karla Berg",
  "Turner Cabrera",
  "Mayra Forbes",
  "Clay Becker",
  "Declan Castillo",
  "Maximilian Barnes",
  "Alanna Rios",
  "Amira Lutz",
  "Parker Logan",
  "Bella Perkins",
  "Nickolas Knox",
  "Martha Beck",
  "Deanna Willis",
  "Branson Richards",
  "Yasmin Ward",
  "Aria Richardson",
  "Lennon James",
  "Ben Garrison",
  "Averie Grant",
  "Mercedes Huang",
  "Jamir Bautista",
  "Turner Contreras",
  "Jackson Miller",
  "Reid Tran",
  "Malcolm Parsons",
  "Christine Ware",
  "Cailyn Sutton",
  "Nehemiah Garcia",
  "Urijah Conner",
  "Yasmin Adkins",
  "Amanda Krueger",
  "Albert Baird",
  "Camron Ramsey",
  "Melina Huynh",
  "Broderick Goodwin",
  "Eliezer Smith",
  "Gaige Mccullough",
  "Mariela Greene",
  "Jacqueline Dunn",
  "Kaylah White",
  "Trinity Logan",
  "Bruce Nicholson",
  "Leandro Terry",
  "Fernando Fisher",
  "Mohammad Nunez",
  "Marin Trujillo",
  "Damien Ibarra",
  "Kieran Malone",
  "Jagger Haney",
  "Kira Neal",
  "Noah Perry",
  "Devyn Velez",
  "Mekhi Rubio",
  "Karsyn Horn",
  "Marcus Boyle",
  "Charlie Olson",
  "Ulises Clay",
  "Alivia Gamble",
  "Micheal Maxwell",
  "Kaya Mata",
  "Lexi Fleming",
  "Abbigail Velez",
  "Raven Poole",
  "Jamir Fernandez",
  "Audrey Rowe",
  "Francis Krause",
  "Abbigail Roach",
  "Karen Thornton",
  "Gwendolyn Jordan",
  "Peter Mcmillan",
  "Ayanna Cruz",
  "Amara Salazar",
  "Alma Sexton",
  "London Leblanc",
  "James Solomon",
  "John Gallegos",
  "Brooklynn Cooley",
  "Nadia Mullen",
  "Desmond Anderson",
  "Teagan Medina",
  "Elisabeth Nixon",
  "Libby Bauer",
  "Alia Stafford",
  "Naomi Huynh",
  "Julia Baldwin",
  "Chana Farmer",
  "Aimee Oconnor",
  "Emilia Frey",
  "Araceli Lucas",
  "Phoenix Barron",
  "Valentino Jackson",
  "Keegan Branch",
  "Briley Mckenzie",
  "Chelsea Levy",
  "Cailyn Tyler",
  "Guadalupe Merritt",
  "Denisse Christensen",
  "Jaylin Espinoza",
  "Liliana Larson",
  "Darryl Pacheco",
  "Larry Fuentes",
  "Amiah Turner",
  "Rudy Christensen",
  "Jamya Osborne",
  "Drew Trevino",
  "Braiden Strickland",
  "Keenan Ellison",
  "Nasir Fisher",
  "Haleigh Bell",
  "Cristal Fitzgerald",
  "Jasper Hunter",
  "Misael Zavala",
  "Roselyn Pratt",
  "Jan Camacho",
  "Rey Hunter",
  "Mayra Ramos",
  "Adrianna Wolfe",
  "Adyson Duffy",
  "Natalie Hull",
  "Alena Velez",
  "Cindy Gallegos",
  "Alana Crane",
  "Jett Roach",
  "Londyn Armstrong",
  "Aditya Dorsey",
  "Maleah Baird",
  "Cristopher Rhodes",
  "Danielle Pratt",
  "Ayden Gamble",
  "Taniyah Roach",
  "Laylah Kidd",
  "Vaughn Duran",
  "Keegan Gregory",
  "Emily Mullen",
  "Christine Jensen",
  "Isaiah Fisher",
  "Zaniyah Huber",
  "Nataly Fernandez",
  "Emanuel Conrad",
  "Deegan Ponce",
  "Claudia Roman",
  "Chaya Patel",
  "Saul Hatfield",
  "Izabella Moyer",
  "Gloria Brady",
  "Jaiden Patel",
  "Presley Sawyer",
  "Bryson Ballard",
  "Marcel Morse",
  "Brodie Simmons",
  "Omari Randolph",
  "Evelin Blackwell",
  "Jewel Hodges",
  "Shaun Hicks",
  "Lucian Parsons",
  "Payton Carrillo",
  "Nicolas Hudson",
  "Danica Aguilar",
  "Reagan Whitney",
  "Kamari Pace",
  "Kendal Stein",
  "Markus Park",
  "Destinee Wu",
  "Zoe Wilkins",
  "Khalil Mayo",
  "Cara Barron",
  "Tyson Ayers",
  "Lilian Meadows",
  "Kyla Farrell",
  "Evie Parker",
  "Daniella Bradford",
  "Emma Gibbs",
  "Stanley Hawkins",
  "Brian Booth",
  "Crystal Lutz",
  "Kimora Dominguez",
  "Matteo Aguirre",
  "Stephen Stokes",
  "Corinne Miles",
  "Sidney Mathews",
  "Franklin Sanchez",
  "Samantha Waters",
  "Raiden Garza",
  "Zaiden Boone",
  "Lukas Mays",
  "Quinn Sosa",
  "Breanna Soto",
  "Aleena Chandler",
  "Darryl Rodriguez",
  "Gia Mcdaniel",
  "Dashawn Prince",
  "Gregory Middleton",
  "Iris Hendrix",
  "Cassius Stevenson",
  "Willow Reilly",
  "Marisa Brennan",
  "Lailah Russell",
  "Jimmy Lambert",
  "Erik Bradshaw",
  "Jorge Gross",
  "Willow Mack",
  "Kai Bates",
  "Ariel Aguirre",
  "Demetrius Ashley",
  "Maximillian Levy",
  "Leon Oconnell",
  "Jeremiah Cortez",
  "Maxwell Charles",
  "Helena Petty",
  "Aliana Willis",
  "Lucy Parker",
  "Ezra Fisher",
  "Bryce Adkins",
  "Julianna Wall",
  "Corbin Glenn",
  "Mylee Lee",
  "Shannon Gould",
  "Kayleigh Zavala",
  "Angelique Kane",
  "Rayan Cole",
  "Evan Huerta",
  "Andres Fischer",
  "Alice Stanton",
  "Aryan Jensen",
  "Vivian Hansen",
  "Dustin Randolph",
  "Jamarcus Trujillo",
  "Abigail Watts",
  "Giselle Martinez",
  "Damaris Bentley",
  "Nathaly Mullins",
  "Anika Cordova",
  "Ryan Morse",
  "Cynthia Hanson",
  "Kyson Melton",
  "Jermaine Osborn",
  "Braeden Benjamin",
  "Elaine Collins",
  "Aiyana Barajas",
  "Jean Wu",
  "Noe Page",
  "Jennifer Wu",
  "Kiersten Ortega",
  "Yesenia Rice",
  "Celia Torres",
  "Brenna Hurley",
  "Hector Dudley",
  "Grady Kim",
  "Amber Massey",
  "Angel Bates",
  "Sherlyn Jimenez",
  "Maleah Wong",
  "Skyla Clark",
  "Annabelle Kramer",
  "Oswaldo Maynard",
  "Zariah Moore",
]

const countries = [
  "Malta",
  "Nepal",
  "Saint Vincent and the Grenadines",
  "Republic of Kosovo",
  "Tonga",
  "Belize",
  "Iran",
  "Bulgaria",
  "Netherlands",
  "Poland",
  "Guinea-Bissau",
  "Scotland",
  "Samoa",
  "Somalia",
  "Palestine",
  "Morocco",
  "Mexico",
  "Falkland Islands",
  "Peru",
  "French Polynesia",
  "The Gambia",
  "Benin",
  "Saudi Arabia",
  "Virgin Islands (U.S.)",
  "Canada",
  "Togo",
  "Saint Martin",
  "Cuba",
  "Bahrain",
  "Andorra",
  "Tuvalu",
  "Cayman Islands",
  "Burkina Faso",
  "New Caledonia",
  "Republic of the Congo",
  "Spain",
  "Panama",
  "Afghanistan",
  "Dominica",
  "San Marino",
  "Israel",
  "Mongolia",
  "Portugal",
  "Montserrat",
  "Tanzania",
  "Armenia",
  "Italy",
  "Svalbard and Jan Mayen",
  "Lebanon",
  "Reunion",
  "Zimbabwe",
  "Lesotho",
  "Norway",
  "Federated States of Micronesia",
  "Slovakia",
  "Costa Rica",
  "Bonaire",
  "Moldova",
  "Gibraltar",
  "Madagascar",
]

const skills = [
  "Copywriting",
  "Sales Funnels",
  "Social media manager",
  "Graphic Design",
  "Lead Generation",
  "Voice Acting",
  "Email Marketing",
  "Logo Design",
  "Brand Style Guide",
  "Game Art",
  "Business Cards & Stationery",
  "Infographic Design",
  "Social Media Marketing",
  "Video Marketing",
  "Content Marketing ",
  "Music Promotion",
  "Articles and blog posts",
  "Proofreading & Editing",
  "Website Content",
  "Product Descriptions",
  "Resume Writing & Cover Letters",
  "LinkedIn Profiles",
  "The Whiteboard & Animated Explainers",
  "Video Editing",
  "Short Video Ads",
  "Character Animation",
  "Animated GIFs",
  "Logo Animation",
  "Intros and outros",
  "Virtual Assistant",
  "Online Tutoring",
  "Gaming",
  "Astrology & Psychics",
  "Modeling & Acting",
  "Fitness Lessons",
  "Dance Lessons",
  "Life Coaching",
]
const levels = ["begginer", "intermediate", "expert"]

function genUsers(i) {
  return {
    fullname: names[i],
    country: countries[getRandomInt(0, countries.length)],
    likedSellers: [],
    likedGigs: [],
    imgUrl: "https://api.lorem.space/image/face?w=500&h=500",
    description: generateWords(getRandomInt(100, 180)),
    skills: [
      skills[getRandomInt(0, skills.length / 2)],
      skills[getRandomInt(skills.length / 2 + 1, skills.length)],
    ],
    level: levels[getRandomInt(0, levels.length)],
    earnings: {
      net: null,
      pending: null,
      expected: null,
    },
    memberSince: `${getRandomInt(2015, 2021)}-${getRandomInt(
      1,
      12
    )}-${getRandomInt(1, 28)}`,
    isSeller: false,
  }
}

const words = [
  "Got",
  "ability",
  "shop",
  "recall",
  "fruit",
  "easy",
  "dirty",
  "giant",
  "shaking",
  "ground",
  "weather",
  "lesson",
  "almost",
  "square",
  "forward",
  "bend",
  "cold",
  "broken",
  "distant",
  "adjective.",
  "enter",
  "mouth",
  "protect",
  "defend",
  "curtain",
  "harmony",
  "dollar",
  "paragraph",
  "sentence",
  "bathtub",
  "blow",
  "rate",
  "sit",
  "stamp",
  "concentration",
  "extract",
  "center",
  "consideration",
  "seem",
  "dominate",
  "sample",
  "capture",
  "still",
  "pool",
  "veil",
  "theme",
  "tourist",
  "night",
  "march",
  "literacy",
  "blonde",
  "yearn",
  "guerrilla",
  "sip",
  "period",
  "secure",
  "grind",
  "species",
  "transform",
  "folk",
  "jet",
  "survey",
  "invite",
  "goalkeeper",
  "gutter",
  "cheap",
  "cathedral",
  "crutch",
  "scenario",
  "biography",
]

function getRandomWord(firstLetterToUppercase = false) {
  const word = words[getRandomInt(0, words.length - 1)]
  return firstLetterToUppercase
    ? word.charAt(0).toUpperCase() + word.slice(1)
    : word
}
function generateWords(length = 10) {
  return (
    [...Array(length)]
      .map((_, i) => getRandomWord(i === 0))
      .join(" ")
      .trim() + "."
  )
}

const listOfUsers = () => {
  const users = []
  for (let i = 0; i < 2; i++) {
    users.push(genUsers(i))
  }
  return users
}
// if you want to use this user genarator it is here

// console.log('LIST OF USERS GENARATOR LINE 635 UTIL SERVICE JS' , listOfUsers())
